In [4]:
import numpy as np

In [11]:
np.random.seed(12345)
data = np.random.randn(5,6)
data

array([[-2.04707659e-01,  4.78943338e-01, -5.19438715e-01,
        -5.55730304e-01,  1.96578057e+00,  1.39340583e+00],
       [ 9.29078767e-02,  2.81746153e-01,  7.69022568e-01,
         1.24643474e+00,  1.00718936e+00, -1.29622111e+00],
       [ 2.74991633e-01,  2.28912879e-01,  1.35291684e+00,
         8.86429341e-01, -2.00163731e+00, -3.71842537e-01],
       [ 1.66902531e+00, -4.38569736e-01, -5.39741446e-01,
         4.76985010e-01,  3.24894392e+00, -1.02122752e+00],
       [-5.77087303e-01,  1.24121276e-01,  3.02613562e-01,
         5.23772068e-01,  9.40277775e-04,  1.34380979e+00]])

In [13]:
a = data.max()

3.248943919430755

In [20]:
b = data.sum(axis=0)
b

array([1.25512986, 0.67515391, 1.3653728 , 2.57789085, 4.22121682,
       0.04792446])

In [21]:
c = data.mean(axis=1)
c

array([0.42637551, 0.35017993, 0.06162847, 0.56590259, 0.28636161])

In [32]:
d = data[data[:,0].argsort(), :]
d

array([[-5.77087303e-01,  1.24121276e-01,  3.02613562e-01,
         5.23772068e-01,  9.40277775e-04,  1.34380979e+00],
       [-2.04707659e-01,  4.78943338e-01, -5.19438715e-01,
        -5.55730304e-01,  1.96578057e+00,  1.39340583e+00],
       [ 9.29078767e-02,  2.81746153e-01,  7.69022568e-01,
         1.24643474e+00,  1.00718936e+00, -1.29622111e+00],
       [ 2.74991633e-01,  2.28912879e-01,  1.35291684e+00,
         8.86429341e-01, -2.00163731e+00, -3.71842537e-01],
       [ 1.66902531e+00, -4.38569736e-01, -5.39741446e-01,
         4.76985010e-01,  3.24894392e+00, -1.02122752e+00]])

In [33]:
e = data[:, data[0].argsort()]
e

array([[-5.55730304e-01, -5.19438715e-01, -2.04707659e-01,
         4.78943338e-01,  1.39340583e+00,  1.96578057e+00],
       [ 1.24643474e+00,  7.69022568e-01,  9.29078767e-02,
         2.81746153e-01, -1.29622111e+00,  1.00718936e+00],
       [ 8.86429341e-01,  1.35291684e+00,  2.74991633e-01,
         2.28912879e-01, -3.71842537e-01, -2.00163731e+00],
       [ 4.76985010e-01, -5.39741446e-01,  1.66902531e+00,
        -4.38569736e-01, -1.02122752e+00,  3.24894392e+00],
       [ 5.23772068e-01,  3.02613562e-01, -5.77087303e-01,
         1.24121276e-01,  1.34380979e+00,  9.40277775e-04]])

In [34]:
import pandas as pd

In [36]:
data = {
        '번호' : [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
        '반' : ['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B'],
        '영어' : [100, 90, 100, 80, 70, 90, 100, 70, 80, 90],
        '국어' : [90, 80, 90, 70, 100, 80, 90, 100, 70, 80],
        '수학' : [80, 100, 80, 90, 80, 100, 70, 80, 90, 100]}
data

{'번호': [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
 '반': ['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B'],
 '영어': [100, 90, 100, 80, 70, 90, 100, 70, 80, 90],
 '국어': [90, 80, 90, 70, 100, 80, 90, 100, 70, 80],
 '수학': [80, 100, 80, 90, 80, 100, 70, 80, 90, 100]}

In [40]:
a = pd.DataFrame(data)
a

번호  반   영어   국어   수학
0   1  A  100   90   80
1   2  A   90   80  100
2   3  A  100   90   80
3   4  A   80   70   90
4   5  A   70  100   80
5   1  B   90   80  100
6   2  B  100   90   70
7   3  B   70  100   80
8   4  B   80   70   90
9   5  B   90   80  100

In [45]:
b = a.drop(['반', '번호'], axis = 'columns')
b

영어   국어   수학
0  100   90   80
1   90   80  100
2  100   90   80
3   80   70   90
4   70  100   80
5   90   80  100
6  100   90   70
7   70  100   80
8   80   70   90
9   90   80  100

In [72]:
b['평균'] = b.mean(axis=1)
c = b
c

영어   국어   수학         평균
0  100   90   80  90.000000
1   90   80  100  90.000000
2  100   90   80  90.000000
3   80   70   90  80.000000
4   70  100   80  83.333333
5   90   80  100  90.000000
6  100   90   70  86.666667
7   70  100   80  83.333333
8   80   70   90  80.000000
9   90   80  100  90.000000

In [77]:
c.loc['평균'] = c.mean(axis=0)
d = c
d

영어     국어     수학         평균
0   100.0   90.0   80.0  90.000000
1    90.0   80.0  100.0  90.000000
2   100.0   90.0   80.0  90.000000
3    80.0   70.0   90.0  80.000000
4    70.0  100.0   80.0  83.333333
5    90.0   80.0  100.0  90.000000
6   100.0   90.0   70.0  86.666667
7    70.0  100.0   80.0  83.333333
8    80.0   70.0   90.0  80.000000
9    90.0   80.0  100.0  90.000000
평균   87.0   85.0   87.0  86.333333