In [1]:
ddata1 = {'name': "kim", "age":20, "address": "seoul"}
ddata1

{'name': 'kim', 'age': 20, 'address': 'seoul'}

In [3]:
ddata1['name']

'kim'

In [4]:
ddata2 = {100: "hundred", True:1, 3232.32:'fvalue'}
ddata2

{100: 'hundred', True: 1, 3232.32: 'fvalue'}

In [7]:
ddata2[100], ddata2[True], ddata2[3232.32]

('hundred', 1, 'fvalue')

In [11]:
ddata3 = dict(name='lee', address='busan', weight=100)
ddata3

{'name': 'lee', 'address': 'busan', 'weight': 100}

In [16]:
ddata4 = dict([('name', 'chio'), ('age', 30), ('height',180)])
ddata4

{'name': 'chio', 'age': 30, 'height': 180}

In [17]:
ddata4['weight'] = 500
ddata4

{'name': 'chio', 'age': 30, 'height': 180, 'weight': 500}

In [18]:
ddata4.keys(), ddata4.values(), ddata4.items()

(dict_keys(['name', 'age', 'height', 'weight']),
 dict_values(['chio', 30, 180, 500]),
 dict_items([('name', 'chio'), ('age', 30), ('height', 180), ('weight', 500)]))

In [20]:
for k in ddata4.keys():
    print(k)

name
age
height
weight


In [22]:
for v in ddata4.values():
    print(v)

chio
30
180
500


In [23]:
for i in ddata4.items():
    print(i)

('name', 'chio')
('age', 30)
('height', 180)
('weight', 500)


In [24]:
for k, v in ddata4.items():
    print(k, v)

name chio
age 30
height 180
weight 500


In [26]:
def person_info(name, age, address):
    print('name: {}, age: {}, address{}'.format(name, age, address))

In [27]:
person_info('kim', age=10, address='busan')

name: kim, age: 10, addressbusan


In [28]:
ddata1 = {'name':'lee', 'age':30, 'address':'busan'}
person_info(**ddata1)

name: lee, age: 30, addressbusan


In [34]:
def person_info2(**data):
    for k, v in data.items():
        print(k, v, sep=':')

In [35]:
person_info2(name='oh', age=10)

name:oh
age:10


In [39]:
def person_info3(**data):
    if 'age' in data:
        print('age:' , data['age'], end=' ')
    if 'name' in data:
        print('name:', data['name'])

In [40]:
person_info3(name='oh', age=10)

age: 10 name: oh


In [50]:
ldata1 = ['red', 'blue', 'green']
print(ldata1)
print(', '.join(ldata1))

['red', 'blue', 'green']
red, blue, green


In [42]:
' '.join(ldata1)

'red blue green'

In [43]:
''.join(ldata1)

'redbluegreen'

In [45]:
'-'.join(ldata1)

'red-blue-green'

In [51]:
id1 = []
for i in range(10):
    id1.append(i)
id1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [52]:
id2 = [i for i in range(10)]
id2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [54]:
id3 = [i for i in range(10) if i%2 == 0]
id3

[0, 2, 4, 6, 8]

In [58]:
id3 = [i if i%2 == 0 else 10 for i in range(10)]
id3

[0, 10, 20, 10, 40, 10, 60, 10, 80, 10]

In [63]:
id3 = [i * j for i in range(2,10) for j in range(1,10)]
print(id3, sep=' ')

[2, 4, 6, 8, 10, 12, 14, 16, 18, 3, 6, 9, 12, 15, 18, 21, 24, 27, 4, 8, 12, 16, 20, 24, 28, 32, 36, 5, 10, 15, 20, 25, 30, 35, 40, 45, 6, 12, 18, 24, 30, 36, 42, 48, 54, 7, 14, 21, 28, 35, 42, 49, 56, 63, 8, 16, 24, 32, 40, 48, 56, 64, 72, 9, 18, 27, 36, 45, 54, 63, 72, 81]


In [67]:
words = 'The quick brown fox jumps over the lagy dog'.split()
ld4 = [[w.upper(), w.lower(), len(w)] for w in words] 
ld4

[['THE', 'the', 3],
 ['QUICK', 'quick', 5],
 ['BROWN', 'brown', 5],
 ['FOX', 'fox', 3],
 ['JUMPS', 'jumps', 5],
 ['OVER', 'over', 4],
 ['THE', 'the', 3],
 ['LAGY', 'lagy', 4],
 ['DOG', 'dog', 3]]

In [71]:
ldatq1 = ['blue', 'green', 'yellow', 'black']
for n, d in enumerate(ldatq1):
    print(n, d)

0 blue
1 green
2 yellow
3 black


In [72]:
ldatq1 = ['blue', 'green', 'yellow', 'black']
for n, d in enumerate(ldatq1, start=1):
    print(n, d)

1 blue
2 green
3 yellow
4 black


In [120]:
ld1 = ['kim', 'lee', 'choi']
ld2 = [20, 10, 50]
ld3 = [180, 150, 170]

for d in zip(ld1, ld2, ld3):
    print(d)
    
[d for a,b,c in zip(ld1, ld2, ld3)]


('kim', 20, 180)
('lee', 10, 150)
('choi', 50, 170)


[('choi', 50, 170), ('choi', 50, 170), ('choi', 50, 170)]

In [83]:
words = 'The quick brown fox jumps over the lagy dog'.split()
data = {k: v for k, v in enumerate(words)}
data

{0: 'The',
 1: 'quick',
 2: 'brown',
 3: 'fox',
 4: 'jumps',
 5: 'over',
 6: 'the',
 7: 'lagy',
 8: 'dog'}

In [84]:
def add (x, y):
    return x + y

add(10,20)

30

In [87]:
add2 = lambda x, y : x + y
add2(10,30)

40

In [94]:
def calc(fv, a, b):
    print(f'a {a} b {b} result {fv(a,b)}')

In [95]:
calc(add, 10, 20)

a 10 b 20 result 30


In [96]:
calc(lambda a, b : a + b, 10, 20)

a 10 b 20 result 30


In [97]:
ldata1 = [2, 4,5,1,1,3,5,4]
ldata1.sort()
ldata1

[1, 1, 2, 3, 4, 4, 5, 5]

In [104]:
ldata2 = [('kim', 80), ('lee', 50), ('choi', 30), ('oh', 40)]
print(ldata2, end='\n\n')

def sfunc(s):
    return s[1]

#ldata2.sort(key=sfunc)
#print(ldata2)

ldata2.sort(key=lambda x : x[1])
print(ldata2)

[('kim', 80), ('lee', 50), ('choi', 30), ('oh', 40)]

[('choi', 30), ('oh', 40), ('lee', 50), ('kim', 80)]


In [109]:
def mf(x):
    return x ** 2

ld1 = [1,2,3,4,5]
ld2 = list(map(mf, ld1))
print(f'{ld2}')
print(list(map(lambda x: x**2, ld1)))

[1, 4, 9, 16, 25]
[1, 4, 9, 16, 25]


In [110]:
ldata = [32.12, 42.23, 34.132]
print(list(map(int, ldata)))

[32, 42, 34]


In [135]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
    def print_info(self):
        print(f'name: {self.name}, age: {self.age}')
        
    def __str__(self):
        return f'{self.name}, {self.age}'

In [136]:
obj = Person('kim', 23)
obj

In [137]:
obj.print_info()

name: kim, age: 23


In [138]:
print(obj)

kim, 23


In [152]:
class InstanceC:
    text_list = []
    
    def add_item(self, text):
        self. text_list.append(text)
        
    def print_list(self):
        print(self.text_list)

one = InstanceC()
one.add_item('first')
one.print_list()

two = InstanceC()
two.add_item('second')
two.print_list()

['first']
['first', 'second']


In [156]:
class InstanceC:
    #text_list = []
    
    def __init__(self):
        self.text_list = []
    
    def add_item(self, text):
        self. text_list.append(text)
        
    def print_list(self):
        print(self.text_list)

one = InstanceC()
one.add_item('first')
one.print_list()

two = InstanceC()
two.add_item('second')
two.print_list()

['first']
['second']


In [157]:
class Phone:
    
    def call(self, p_number):
        print('{} 에게 전화를 겁니다.'.format(p_number))
    
    def send_message(self, p_number, msg):
        print("{} 에게 {} 메세지를 보냅니다.".format(p_number, msg))

p = Phone()
p.call('010-8406-4444')
p.send_message('010-158-124', 'test')

010-8406-4444 에게 전화를 겁니다.
010-158-124 에게 test 메세지를 보냅니다.


In [158]:
class sPhone(Phone):
    def playMusic(self, title):
        print('{} 를 재생합니다.'.format(title))
    def takePicture(self):
        print('사진을 찍습니다.')
        
sp = sPhone()
sp.call('1254-1257-1257')
sp.send_message('010-158-124', 'test')
sp.playMusic('abcd')
sp.takePicture()

1254-1257-1257 에게 전화를 겁니다.
010-158-124 에게 test 메세지를 보냅니다.
abcd 를 재생합니다.
사진을 찍습니다.


In [159]:
file = open("test.txt", 'w')
file.write("hi hello!!!")
file.close()

In [160]:
file2 = open('test.txt', 'r')
rstr = file2.read()
print('read string: ', rstr)
file2.close()

read string:  hi hello!!!


In [161]:
iter1 = range(3).__iter__()
iter1

In [163]:
iter1.__next__()

0

In [164]:
iter1.__next__()

1

In [165]:
iter1.__next__()

2

In [166]:
iter1.__next__()

StopIteration: 

In [167]:
ldata = [10,20,30]
iter2 = ldata.__iter__()
iter2

In [169]:
iter2.__next__()

10

In [170]:
iter2.__next__()

20

In [171]:
iter2.__next__()

30

In [172]:
iter2.__next__()

StopIteration: 

In [177]:
ddata1 = {'a': 1, 'b': 2}
iter1 = ddata1.__iter__()

In [178]:
iter1.__next__()

'a'

In [181]:
iter1.__next__()

StopIteration: 

In [182]:
iter1.__next__()

StopIteration: 

In [187]:
class CRange:
    def __init__(self, start, end):
        self.current = start
        self.end = end
        
    def __iter__(self):
        return self
    
    def __next__(self):
        if self.current < self.end:
            rvalue = self.current
            self.current += 1
            return rvalue
        else:
            raise StopIteration()
            
try:
    for i in CRange(0, 4):
        print(i)
except StopIteration:
    print("ddddddd")
finally:
    print('end')

0
1
2
3
end


In [191]:
infile1 = open('FirstPresidents.txt', 'r')

for line in infile1:
    print(line.rstrip())

George Washington
John Adams
Thomas Jefferson


In [195]:
infile1 = open('FirstPresidents.txt', 'r')

ldata1 = [line.rstrip() for line in infile1]
print(ldata1)

['George Washington', 'John Adams', 'Thomas Jefferson']


In [201]:
infile1 = open('States.txt', 'r')
outfile1 = open('StateAlpha.txt', 'w')

ldata = [line for line in infile1]
ldata.sort()
outfile1.write(lines(ldata))
infile1.close()
outfile1.close()

TypeError: write() argument must be str, not list

In [209]:
infile1 = open('States.txt', 'r')
outfile1 = open('StateSort.txt', 'w')

ldata = [ line for line in infile1]
#ldata.sort(key=lambda x : len(x), reverse=True)
ldata.sort(key=len, reverse=True)

outfile1.writelines(ldata)
infile1.close()
outfile1.close()

In [215]:
infile1 = open('USPres.txt', 'r')
infile2 = open('VPres.txt', 'r')
outfile1 = open('Both.txt', 'w')

vList1 = [line for line in infile1]
v#List2 = [line for line in infile2]

for p in infile2:
    if p in vList1:
        print(p)
        outfile1.write(p)
        
infile1.close()
infile2.close()

outfile1.close()

John Adams

Thomas Jefferson

Martin Van Buren

John Tyler

Millard Fillmore

Andrew Johnson

Chester Arthur

Theodore Roosevelt

Calvin Coolidge

Harry Truman

Richard Nixon

Lyndon Johnson

Gerald Ford

George H. W. Bush



In [225]:
infile1 = open('USPres.txt', 'r')
infile2 = open('VPres.txt', 'r')
outfile1 = open('Both2.txt', 'w')

s1 = {line for line in infile1}
s2 = {line for line in infile2}

outdata = s1.intersection(s2)
ldata = sorted(outdata)
print(ldata)

outfile1.writelines(ldata)
infile1.close()
infile2.close()

outfile1.close()

['Andrew Johnson\n', 'Calvin Coolidge\n', 'Chester Arthur\n', 'George H. W. Bush\n', 'Gerald Ford\n', 'Harry Truman\n', 'John Adams\n', 'John Tyler\n', 'Lyndon Johnson\n', 'Martin Van Buren\n', 'Millard Fillmore\n', 'Richard Nixon\n', 'Theodore Roosevelt\n', 'Thomas Jefferson\n']


In [226]:
with open('test.txt', 'r') as file:
    rstr = file.read()
    print(rstr)

hi hello!!!


In [235]:
import os

if not os.path.isdir('log'):
    os.mkdir('log')
    
if os.path.exists('log/count_log.txt'):
    f= open('log/count_log.txt', 'w', encoding='utf8')
    f.write('기록이 시작됩니다. \n\n')
    f.close()

import random, datetime
with open ('log/count_log.txt', 'a', encoding='utf8') as f:
    for i in range(1,10):
        timestr = str(datetime.datetime.now())
        rvalue = random.random() * 1000000
        log_str = timestr + str(rvalue) + '값 생성\n'
        f.write(log_str)
        


In [237]:
import numpy as np

data1 = [1,2,3.4, 5]
print(data1, type(data1))

arr1 = np.array(data1)
arr1



[1, 2, 3.4, 5] <class 'list'>


array([1. , 2. , 3.4, 5. ])

In [238]:
np.array(data1, dtype=np.int32)

array([1, 2, 3, 5], dtype=int32)

In [239]:
data2 = [[1,2,3,4],[5,6,7,8]]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [240]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [243]:
arr2.shape, arr2.dtype

((2, 4), dtype('int64'))

In [249]:
data3 = [[1,2,3,4],[1,2,3,4],[1,2,3,4]]
arr3 = np.array(data3)
arr3.shape, arr3.dtype

((3, 4), dtype('int64'))

In [252]:
arr4 = np.arange(0,10,1)
arr4, type(arr4)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

In [254]:
arr5=np.linspace(-3,3,10)
arr5

array([-3.        , -2.33333333, -1.66666667, -1.        , -0.33333333,
        0.33333333,  1.        ,  1.66666667,  2.33333333,  3.        ])

In [256]:
arr6 = np.zeros([3,4])
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [257]:
arr7 = np.ones([3,4])
arr7

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [258]:
arr7 = np.empty([3,4])
arr7

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [260]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [261]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [262]:
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [263]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [264]:
arr1 * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [265]:
1/arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [267]:
arr1 > arr2

array([[False, False, False],
       [False, False, False]])

In [268]:
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [270]:
arr3[5], arr3[2:7]

(5, array([2, 3, 4, 5, 6]))

In [273]:
arr3[0] = 10
arr3

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [280]:
arr3 = np.array([[1,2,3, 4],[4,5,6, 7],[7,8,9, 10]])
arr3

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [281]:
arr3[1][1], arr3[1,1]

(5, 5)

In [282]:
arr3[1:,2:]

array([[ 6,  7],
       [ 9, 10]])

In [283]:
arr3[1:][2:]

array([], shape=(0, 4), dtype=int64)